version: '3'
services:
  ascent-discovery:
    image: ascent/ascent-discovery
    hostname: ascent-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=aws-ci
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
        - ascentnet
  
  ascent-config:
    image: ascent/ascent-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=aws-ci
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_HOST=${VAULT_HOST}
      - VAULT_SCHEME=https
    networks:
        - ascentnet

  ascent-dashboard:
    image: ascent/ascent-
    ports:
    - 8763
    environment:
      - SPRING_PROFILES_ACTIVE=aws-ci
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
        - ascentnet
networks:
  ascentnet:
    driver: overlay