version: "3.3"
services:
  ascent-dashboard:
    image: ascent/ascent-dashboard
    build: 
      context: ../
    ports:
     - "8763:8763"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    depends_on:
      - ascent-config
      - ascent-discovery
    networks:
        - ascentnet
networks: 
  ascentnet:
    driver: bridge
